### ISSUE TITLE
Trying to create Private K8s Cluster with the example given 

### ISSUE THREAD

**Issue by rajrajen-juul** [gruntwork-io/terraform-google-gke#62] opened 2019-09-16 19:09 UTC
**Thanks for the Private K8s Cluster Example Code. It is useful** 
https://github.com/gruntwork-io/terraform-google-gke/blob/master/examples/gke-private-cluster/variables.tf#L47
 all 3 CIDR ranges are "master_ipv4_cidr_block" is  "10.5.0.0/28" , "vpc_cidr_block" is "10.3.0.0/16" and "vpc_secondary_cidr_block"  is "10.4.0.0/16"

But in my case due to various CIDR block range those are little bit constrained still getting the following 
 all 3 CIDR ranges are "master_ipv4_cidr_block" is  "10.32.98.0/28" , "vpc_cidr_block" is "10.32.96.0/24" and "vpc_secondary_cidr_block"  is "10.32.97.0/24"

And I am getting the following error 

`"tierSettings": {
 "tier": "STANDARD"
},
"selfLink": "https://container.googleapis.com/v1beta1/projects/my-sandbox/locations/us-central1/clusters/sb-pvt-cluster",
"zone": "us-central1",
"endpoint": "34.68.176.42",
"initialClusterVersion": "1.14.3-gke.11",
"currentMasterVersion": "1.14.3-gke.11",
"currentNodeVersion": "1.14.3-gke.11",
"createTime": "2019-09-16T18:45:28+00:00",
"status": "ERROR",
"statusMessage": "\n\t(1) deploy error: Not all instances running in IGM after 12.294175155s. Expect 1. Current errors: [INVALID_FIELD_VALUE]: Instance 'gke-sb-pvt-cluster-default-pool-78b0666e-fjqd' creation failed: Invalid value for field 'resource.networkInterfaces[0].aliasIpRanges[0].ipCidrRange': '/24'. CIDR range for alias IP range must be within the specified subnetwork. (when acting as '902699685401@cloudservices.gserviceaccount.com')\n\t(2) deploy error: Not all instances running in IGM after 12.636626322s. Expect 1. Current errors: [INVALID_FIELD_VALUE]: Instance 'gke-sb-pvt-cluster-default-pool-14f555fd-p8c0' creation failed: Invalid value for field 'resource.networkInterfaces[0].aliasIpRanges[0].ipCidrRange': '/24'. CIDR range for alias IP range must be within the specified subnetwork. (when acting as '902699685401@cloudservices.gserviceaccount.com')\n\t(3) deploy error: Not all instances running in IGM after 14.673528039s. Expect 1. Current errors: [INVALID_FIELD_VALUE]: Instance 'gke-sb-pvt-cluster-default-pool-7f5795dc-zzbs' creation failed: Invalid value for field 'resource.networkInterfaces[0].aliasIpRanges[0].ipCidrRange': '/24'. CIDR range for alias IP range must be within the specified subnetwork. (when acting as '902699685401@cloudservices.gserviceaccount.com').",
"servicesIpv4Cidr": "10.32.97.0/28",
"instanceGroupUrls": [
 "https://www.googleapis.com/compute/v1/projects/my-sandbox/zones/us-central1-b/instanceGroupManagers/gke-sb-pvt-cluster-default-pool-78b0666e-grp",
 "https://www.googleapis.com/compute/v1/projects/my-sandbox/zones/us-central1-c/instanceGroupManagers/gke-sb-pvt-cluster-default-pool-7f5795dc-grp",
 "https://www.googleapis.com/compute/v1/projects/my-sandbox/zones/us-central1-a/instanceGroupManagers/gke-sb-pvt-cluster-default-pool-14f555fd-grp"
],
"currentNodeCount": 3,
"location": "us-central1",
"conditions": [
 {
  "message": "[INVALID_FIELD_VALUE]: Instance 'gke-sb-pvt-cluster-default-pool-78b0666e-fjqd' creation failed: Invalid value for field 'resource.networkInterfaces[0].aliasIpRanges[0].ipCidrRange': '/24'. CIDR range for alias IP range must be within the specified subnetwork. (when acting as '902699685401@cloudservices.gserviceaccount.com')"
 },
 {
  "message": "[INVALID_FIELD_VALUE]: Instance 'gke-sb-pvt-cluster-default-pool-14f555fd-p8c0' creation failed: Invalid value for field 'resource.networkInterfaces[0].aliasIpRanges[0].ipCidrRange': '/24'. CIDR range for alias IP range must be within the specified subnetwork. (when acting as '902699685401@cloudservices.gserviceaccount.com')"
 }`

**Comment by rajrajen-juul** [comment] 2019-09-16 19:11
Attaching the same error content in a TXT file as well..

**Comment by rajrajen-juul** [comment] 2019-09-16 19:12
[my.pvt.k8s.error.txt](https://github.com/gruntwork-io/terraform-google-gke/files/3617801/my.pvt.k8s.error.txt)
Uploading the above error in TXT file as well .

**Comment by autero1** [comment] 2019-09-17 08:16
Hi @rajrajen-juul I believe you have an issue with your network ranges. When configuring your networks / VPCs, refer to the `vpc-network` documentation: https://github.com/gruntwork-io/terraform-google-network/tree/master/modules/vpc-network

**Comment by rajrajen-juul** [comment] 2019-09-17 22:03
**Increased CIDR Block from /24 to /20**

All 3 CIDR ranges are reset to  "master_ipv4_cidr_block" is "10.32.98.0/28" , "vpc_cidr_block" is "10.32.96.0/20" and "vpc_secondary_cidr_block" is "10.32.112.0/20"  and  **"cidr_subnetwork_width_delta" as 4** 
. Its basically forced me to increase the range from /24 to /20 and hence to keep the subnets created .

**Checking the GKE cluster pod / services IP Range** 

Then I am seeing the public-serivces is used in _**Terraform**_ 
`  
  ip_allocation_policy {
    cluster_secondary_range_name  = var.cluster_secondary_range_name
    services_secondary_range_name = var.cluster_secondary_range_name
  }
`

But the "public-services" in the subnet - secondary CIDR block in the _**Terraform Plan**_
![image](https://user-images.githubusercontent.com/50118723/65081871-7503a280-d959-11e9-8b77-ff8d87a10932.png)

Actual "Public Services" in the **Network** page
![image](https://user-images.githubusercontent.com/50118723/65082483-e98b1100-d95a-11e9-9f52-b005fadd5306.png)

When I looked at cluster creation it failed with **[IP_SPACE_EXHAUSTED]**

(1) deploy error: Not all instances running in IGM after 1m13.055459544s. Expect 1. Current errors: [IP_SPACE_EXHAUSTED]: Instance 'gke-sb-pvt-cluster-default-pool-ade9854f-70v1' creation failed: IP space of 'projects/my-sandbox/regions/us-central1/subnetworks/sb-pvt-cl-public-services-477c216b85986fde' is exhausted. (2) deploy error: Not all instances running in IGM after 2m24.501460274s. Expect 1. Current errors: [IP_SPACE_EXHAUSTED]: Instance 'gke-sb-pvt-cluster-default-pool-78e03855-cfg8' creation failed: IP space of 'projects/my-sandbox/regions/us-central1/subnetworks/sb-pvt-cl-public-services-477c216b85986fde' is exhausted. .

![image](https://user-images.githubusercontent.com/50118723/65082969-21468880-d95c-11e9-8960-dc8d0c7be2e3.png)

**Comment by jakesyl** [comment] 2019-11-27 10:13
Any update on this? I have the same issue

**Comment by autero1** [comment] 2019-11-28 08:38
@jakesyl could you provide a bit more context? How are you using the module, what settings do you have and what exact error are you getting. Could you share your configuration, so we could try and reproduce it. Thanks!

**Comment by jakesyl** [comment] 2019-12-06 21:04
@autero1, yeah, so the issue was just `/20` restricts us to 16 vms so we had to reform the cluster with `/14` and move everything over after using this to bootstrap our initial cluster

**Comment by Etiene** [comment] 2022-01-20 15:32
Apologies for the delay in responding to this issue. Please see below: 

### Sunset notice

We believe there is an opportunity to create a truly outstanding developer experience for deploying to the cloud, however developing this vision requires that we temporarily limit our focus to just one cloud. Gruntwork has hundreds of customers currently using AWS, so we have temporarily suspended our maintenance efforts on this repo. Once we have implemented and validated our vision for the developer experience on the cloud, we look forward to picking this up. In the meantime, you are welcome to use this code in accordance with the open source license, however we will not be responding to GitHub Issues or Pull Requests.

If you wish to be the maintainer for this project, we are open to considering that. Please contact us at support@gruntwork.io.

**Comment by eak12913** [comment] 2023-03-29 17:27
Closing due to [repo sunset](https://github.com/gruntwork-io/terraform-google-gke#sunset-notice)

**Closed by eak12913** 2023-03-29 17:27 UTC
